# Base URL
@baseUrl = http://localhost:5800/users
@adminToken = {{loginAdmin.response.body.token}}

### REGISTER ADMIN USER (Public - No Authorization Needed)
POST {{baseUrl}}/register
Content-Type: application/json

{
  "username":"Timo",
  "email":"timo@example.com",
  "password":"1234567"
  }

### LOGIN ADMIN USER
# @name loginAdmin
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email":"collector@example.com",
  "password":"collector"
}

### FETCH ALL USERS AND COLLECTORS (Admin Only)
GET {{baseUrl}}/fetch-all-users
Content-Type: application/json


### FETCH USER BY ROLE(USER) (Collector or Admin)
GET {{baseUrl}}/fetchRole-users
Content-Type: application/json


### FETCH SINGLE USER (Any Authenticated User)
GET {{baseUrl}}/64b0cf59-afcd-48c9-badc-64b00eb6821f
Content-Type: application/json


### UPDATE USER PROFILE (Any Authenticated User)
PUT {{baseUrl}}/admintim@example.com
Content-Type: application/json


{
  "password":"1234567",
  "profile_picture":"picture.jpg"
}

### SWITCH TO COLLECTOR ROLE (Admin Only)
PATCH {{baseUrl}}/switchManagerRole/64b0cf59-afcd-48c9-badc-64b00eb6821f
Content-Type: application/json


### SWITCH TO ADMIN ROLE (Admin Only)
PATCH {{baseUrl}}/switchAdminRole/64b0cf59-afcd-48c9-badc-64b00eb6821f
Content-Type: application/json


### REVOKE PRIVILEGES FROM MANAGER AND ADMIN ROLE TO USERS (Admin Only)
PATCH {{baseUrl}}/revokePrivileges/7d02a16b-70fd-417d-828d-4a6701dde7e7
Content-Type: application/json


### DEACTIVATE USER (Admin Only)
PATCH {{baseUrl}}/deactivateUser/029f5ee7-8439-4337-9847-b9d862f14757
Content-Type: application/json


### ACTIVATE USER (Admin Only)
PATCH {{baseUrl}}/activateUser/029f5ee7-8439-4337-9847-b9d862f14757
Content-Type: application/json
