  ###REGISTER USER
POST http://localhost:5800/users/register
Content-Type: application/json

{
    "username": "Collector",
    "email": "collector@example.com",
    "password": "collector"
}

###LOGIN USER
POST http://localhost:5800/users/login
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "1234567"
}

###FETCH ALL USERS AND COLLECTORS
GET http://localhost:5800/users/fetch-all-users
Content-Type: application/json


### FETCH SINGLE USER
GET http://localhost:5800/users/7d02a16b-70fd-417d-828d-4a6701dde7e7
Content-Type: application/json


### FETCH USER BY ROLE(USER)
GET http://localhost:5800/users/fetchRole-users
Content-Type: application/json


###UPDATE USER PROFILE
PUT http://localhost:5800/users/admintim@example.com
Content-Type: application/json

{
  "password": "1234567",
  "profile_picture": "picture.jpg"
}


###SWITCH TO COLLECTOR ROLE
PUT http://localhost:5800/users/switchManagerRole/c640d40b-0018-4ddd-8e80-ec0e930c5916
Content-Type: application/json


###SWITCH TO ADMIN ROLE
PUT http://localhost:5800/users/switchAdminRole/451abb08-e19c-4af2-990e-1ed0fe186862
Content-Type: application/json


###REVOKE PRIVILEGES FROM MANAGER AND ADMIN ROLE TO USERS
PUT http://localhost:5800/users/revokePrivileges/7d02a16b-70fd-417d-828d-4a6701dde7e7
Content-Type: application/json


###DEACTIVATE USER
PUT http://localhost:5800/users/deactivateUser/7d02a16b-70fd-417d-828d-4a6701dde7e7
Content-Type: application/json


###ACTIVATE USER
PUT http://localhost:5800/users/activateUser/7d02a16b-70fd-417d-828d-4a6701dde7e7
Content-Type: application/json